export type StockItem = {
  name: string;
  ticker: string;
  sector: string;
  country: string;
  market?: string;
};

export const STOCK_LIST: StockItem[] = [
  // ── KOSPI ───────────────────────────────────────────────────────────────
  { name: '삼성전자',       ticker: '005930', sector: 'IT/반도체',  country: 'kr', market: 'KOSPI' },
  { name: 'SK하이닉스',     ticker: '000660', sector: 'IT/반도체',  country: 'kr', market: 'KOSPI' },
  { name: 'LG에너지솔루션', ticker: '373220', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: '삼성바이오로직스',ticker: '207940', sector: '바이오',     country: 'kr', market: 'KOSPI' },
  { name: '현대차',         ticker: '005380', sector: '소비재',     country: 'kr', market: 'KOSPI' },
  { name: '삼성SDI',        ticker: '006400', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: 'LG화학',         ticker: '051910', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: 'POSCO홀딩스',    ticker: '005490', sector: '기타',       country: 'kr', market: 'KOSPI' },
  { name: '카카오',         ticker: '035720', sector: 'IT/플랫폼', country: 'kr', market: 'KOSPI' },
  { name: '현대모비스',     ticker: '012330', sector: '소비재',     country: 'kr', market: 'KOSPI' },
  { name: 'KB금융',         ticker: '105560', sector: '금융',       country: 'kr', market: 'KOSPI' },
  { name: '신한지주',       ticker: '055550', sector: '금융',       country: 'kr', market: 'KOSPI' },
  { name: '셀트리온',       ticker: '068270', sector: '바이오',     country: 'kr', market: 'KOSPI' },
  { name: 'LG전자',         ticker: '066570', sector: '소비재',     country: 'kr', market: 'KOSPI' },
  { name: 'NAVER',          ticker: '035420', sector: 'IT/플랫폼', country: 'kr', market: 'KOSPI' },
  { name: '기아',           ticker: '000270', sector: '소비재',     country: 'kr', market: 'KOSPI' },
  { name: 'SK이노베이션',   ticker: '096770', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: '하나금융지주',   ticker: '086790', sector: '금융',       country: 'kr', market: 'KOSPI' },
  { name: 'SK텔레콤',       ticker: '017670', sector: 'IT/플랫폼', country: 'kr', market: 'KOSPI' },
  { name: 'KT',             ticker: '030200', sector: 'IT/플랫폼', country: 'kr', market: 'KOSPI' },
  { name: 'KT&G',           ticker: '033780', sector: '소비재',     country: 'kr', market: 'KOSPI' },
  { name: '우리금융지주',   ticker: '316140', sector: '금융',       country: 'kr', market: 'KOSPI' },
  { name: '한국전력',       ticker: '015760', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: '삼성물산',       ticker: '028260', sector: '기타',       country: 'kr', market: 'KOSPI' },
  { name: 'SK',             ticker: '034730', sector: '기타',       country: 'kr', market: 'KOSPI' },
  { name: '카카오뱅크',     ticker: '323410', sector: '금융',       country: 'kr', market: 'KOSPI' },
  { name: 'LG',             ticker: '003550', sector: '기타',       country: 'kr', market: 'KOSPI' },
  { name: '포스코퓨처엠',   ticker: '003670', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: '한화에어로스페이스', ticker: '012450', sector: '기타',   country: 'kr', market: 'KOSPI' },
  { name: '두산에너빌리티', ticker: '034020', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: '고려아연',       ticker: '010130', sector: '기타',       country: 'kr', market: 'KOSPI' },
  { name: '한국항공우주',   ticker: '047810', sector: '기타',       country: 'kr', market: 'KOSPI' },
  { name: '현대중공업',     ticker: '329180', sector: '기타',       country: 'kr', market: 'KOSPI' },
  { name: '크래프톤',       ticker: '259960', sector: 'IT/플랫폼', country: 'kr', market: 'KOSPI' },
  { name: '카카오페이',     ticker: '377300', sector: '금융',       country: 'kr', market: 'KOSPI' },
  { name: '삼성생명',       ticker: '032830', sector: '금융',       country: 'kr', market: 'KOSPI' },
  { name: 'GS',             ticker: '078930', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: 'S-Oil',          ticker: '010950', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: '롯데케미칼',     ticker: '011170', sector: '기타',       country: 'kr', market: 'KOSPI' },
  { name: '한국가스공사',   ticker: '036460', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: 'DB하이텍',       ticker: '000990', sector: 'IT/반도체',  country: 'kr', market: 'KOSPI' },
  { name: '삼성전기',       ticker: '009150', sector: 'IT/반도체',  country: 'kr', market: 'KOSPI' },
  { name: '한온시스템',     ticker: '018880', sector: '소비재',     country: 'kr', market: 'KOSPI' },
  { name: 'LS ELECTRIC',    ticker: '010120', sector: '에너지',     country: 'kr', market: 'KOSPI' },
  { name: '현대건설',       ticker: '000720', sector: '기타',       country: 'kr', market: 'KOSPI' },
  { name: 'GS건설',         ticker: '006360', sector: '기타',       country: 'kr', market: 'KOSPI' },

  // ── KOSDAQ ──────────────────────────────────────────────────────────────
  { name: '에코프로비엠',    ticker: '247540', sector: '에너지',     country: 'kr', market: 'KOSDAQ' },
  { name: '에코프로',        ticker: '086520', sector: '에너지',     country: 'kr', market: 'KOSDAQ' },
  { name: 'HLB',             ticker: '028300', sector: '바이오',     country: 'kr', market: 'KOSDAQ' },
  { name: '알테오젠',        ticker: '196170', sector: '바이오',     country: 'kr', market: 'KOSDAQ' },
  { name: '리노공업',        ticker: '058470', sector: 'IT/반도체',  country: 'kr', market: 'KOSDAQ' },
  { name: '클래시스',        ticker: '214150', sector: '바이오',     country: 'kr', market: 'KOSDAQ' },
  { name: '주성엔지니어링',  ticker: '036930', sector: 'IT/반도체',  country: 'kr', market: 'KOSDAQ' },
  { name: '레인보우로보틱스',ticker: '277810', sector: 'IT/반도체',  country: 'kr', market: 'KOSDAQ' },
  { name: '파마리서치',      ticker: '214450', sector: '바이오',     country: 'kr', market: 'KOSDAQ' },
  { name: '셀트리온헬스케어',ticker: '091990', sector: '바이오',     country: 'kr', market: 'KOSDAQ' },
  { name: '엔켐',            ticker: '348370', sector: '에너지',     country: 'kr', market: 'KOSDAQ' },
  { name: '카카오게임즈',    ticker: '293490', sector: 'IT/플랫폼', country: 'kr', market: 'KOSDAQ' },
  { name: '펄어비스',        ticker: '263750', sector: 'IT/플랫폼', country: 'kr', market: 'KOSDAQ' },
  { name: '넷마블',          ticker: '251270', sector: 'IT/플랫폼', country: 'kr', market: 'KOSDAQ' },
  { name: 'HPSP',            ticker: '403870', sector: 'IT/반도체',  country: 'kr', market: 'KOSDAQ' },
  { name: '이오테크닉스',    ticker: '039030', sector: 'IT/반도체',  country: 'kr', market: 'KOSDAQ' },
  { name: '솔브레인',        ticker: '357780', sector: 'IT/반도체',  country: 'kr', market: 'KOSDAQ' },
  { name: '엘앤에프',        ticker: '066970', sector: '에너지',     country: 'kr', market: 'KOSDAQ' },

  // ── 미국 (US) ───────────────────────────────────────────────────────────
  { name: 'Apple',           ticker: 'AAPL',   sector: 'IT/반도체',  country: 'us', market: 'NASDAQ' },
  { name: 'Microsoft',       ticker: 'MSFT',   sector: 'IT/플랫폼', country: 'us', market: 'NASDAQ' },
  { name: 'NVIDIA',          ticker: 'NVDA',   sector: 'IT/반도체',  country: 'us', market: 'NASDAQ' },
  { name: 'Amazon',          ticker: 'AMZN',   sector: 'IT/플랫폼', country: 'us', market: 'NASDAQ' },
  { name: 'Alphabet (Google)',ticker: 'GOOGL',  sector: 'IT/플랫폼', country: 'us', market: 'NASDAQ' },
  { name: 'Meta',            ticker: 'META',   sector: 'IT/플랫폼', country: 'us', market: 'NASDAQ' },
  { name: 'Tesla',           ticker: 'TSLA',   sector: '소비재',     country: 'us', market: 'NASDAQ' },
  { name: 'AMD',             ticker: 'AMD',    sector: 'IT/반도체',  country: 'us', market: 'NASDAQ' },
  { name: 'Netflix',         ticker: 'NFLX',   sector: 'IT/플랫폼', country: 'us', market: 'NASDAQ' },
  { name: 'Broadcom',        ticker: 'AVGO',   sector: 'IT/반도체',  country: 'us', market: 'NASDAQ' },
  { name: 'Qualcomm',        ticker: 'QCOM',   sector: 'IT/반도체',  country: 'us', market: 'NASDAQ' },
  { name: 'Intel',           ticker: 'INTC',   sector: 'IT/반도체',  country: 'us', market: 'NASDAQ' },
  { name: 'Costco',          ticker: 'COST',   sector: '소비재',     country: 'us', market: 'NASDAQ' },
  { name: 'TSMC',            ticker: 'TSM',    sector: 'IT/반도체',  country: 'us', market: 'NYSE' },
  { name: 'JP Morgan Chase', ticker: 'JPM',    sector: '금융',       country: 'us', market: 'NYSE' },
  { name: 'Visa',            ticker: 'V',      sector: '금융',       country: 'us', market: 'NYSE' },
  { name: 'Mastercard',      ticker: 'MA',     sector: '금융',       country: 'us', market: 'NYSE' },
  { name: 'Exxon Mobil',     ticker: 'XOM',    sector: '에너지',     country: 'us', market: 'NYSE' },
  { name: 'Johnson & Johnson',ticker: 'JNJ',   sector: '바이오',     country: 'us', market: 'NYSE' },
  { name: 'Eli Lilly',       ticker: 'LLY',    sector: '바이오',     country: 'us', market: 'NYSE' },
  { name: 'UnitedHealth',    ticker: 'UNH',    sector: '바이오',     country: 'us', market: 'NYSE' },
  { name: 'Pfizer',          ticker: 'PFE',    sector: '바이오',     country: 'us', market: 'NYSE' },
  { name: 'Berkshire Hathaway',ticker: 'BRK-B',sector: '금융',       country: 'us', market: 'NYSE' },
  { name: 'Walmart',         ticker: 'WMT',    sector: '소비재',     country: 'us', market: 'NYSE' },
  { name: 'Disney',          ticker: 'DIS',    sector: '소비재',     country: 'us', market: 'NYSE' },
  { name: 'Salesforce',      ticker: 'CRM',    sector: 'IT/플랫폼', country: 'us', market: 'NYSE' },
  { name: 'Oracle',          ticker: 'ORCL',   sector: 'IT/플랫폼', country: 'us', market: 'NYSE' },
  { name: 'Uber',            ticker: 'UBER',   sector: 'IT/플랫폼', country: 'us', market: 'NYSE' },
  { name: 'Airbnb',          ticker: 'ABNB',   sector: '소비재',     country: 'us', market: 'NASDAQ' },
  { name: 'Moderna',         ticker: 'MRNA',   sector: '바이오',     country: 'us', market: 'NASDAQ' },
  { name: 'Coupang',         ticker: 'CPNG',   sector: 'IT/플랫폼', country: 'us', market: 'NYSE' },
  { name: 'Block (Square)',  ticker: 'SQ',     sector: '금융',       country: 'us', market: 'NYSE' },
  { name: 'Spotify',         ticker: 'SPOT',   sector: 'IT/플랫폼', country: 'us', market: 'NYSE' },
  { name: 'Palantir',        ticker: 'PLTR',   sector: 'IT/플랫폼', country: 'us', market: 'NYSE' },
  { name: 'Snowflake',       ticker: 'SNOW',   sector: 'IT/플랫폼', country: 'us', market: 'NYSE' },
  { name: 'Chevron',         ticker: 'CVX',    sector: '에너지',     country: 'us', market: 'NYSE' },
  { name: 'Palo Alto Networks',ticker: 'PANW', sector: 'IT/플랫폼', country: 'us', market: 'NASDAQ' },
];

export const CRYPTO_LIST: StockItem[] = [
  { name: '비트코인',     ticker: 'BTC',   sector: '가상자산', country: 'crypto' },
  { name: '이더리움',     ticker: 'ETH',   sector: '가상자산', country: 'crypto' },
  { name: '리플',         ticker: 'XRP',   sector: '가상자산', country: 'crypto' },
  { name: '솔라나',       ticker: 'SOL',   sector: '가상자산', country: 'crypto' },
  { name: '바이낸스코인', ticker: 'BNB',   sector: '가상자산', country: 'crypto' },
  { name: '에이다',       ticker: 'ADA',   sector: '가상자산', country: 'crypto' },
  { name: '도지코인',     ticker: 'DOGE',  sector: '가상자산', country: 'crypto' },
  { name: '폴리곤',       ticker: 'MATIC', sector: '가상자산', country: 'crypto' },
  { name: '체인링크',     ticker: 'LINK',  sector: '가상자산', country: 'crypto' },
  { name: '아발란체',     ticker: 'AVAX',  sector: '가상자산', country: 'crypto' },
  { name: '앱토스',       ticker: 'APT',   sector: '가상자산', country: 'crypto' },
  { name: '수이',         ticker: 'SUI',   sector: '가상자산', country: 'crypto' },
  { name: '클레이튼',     ticker: 'KLAY',  sector: '가상자산', country: 'crypto' },
  { name: '위믹스',       ticker: 'WEMIX', sector: '가상자산', country: 'crypto' },
  { name: '샌드박스',     ticker: 'SAND',  sector: '가상자산', country: 'crypto' },
  { name: '유니스왑',     ticker: 'UNI',   sector: '가상자산', country: 'crypto' },
  { name: '코스모스',     ticker: 'ATOM',  sector: '가상자산', country: 'crypto' },
  { name: '스텔라루멘',   ticker: 'XLM',   sector: '가상자산', country: 'crypto' },
];

export function searchStocks(query: string, type: 'stock' | 'crypto' | 'gold'): StockItem[] {
  if (type === 'gold' || !query.trim()) return [];
  const list = type === 'crypto' ? CRYPTO_LIST : STOCK_LIST;
  const q = query.toLowerCase();
  return list.filter(s =>
    s.name.toLowerCase().includes(q) || s.ticker.toLowerCase().includes(q)
  );
}
