export type StockItem = {
  name: string;
  ticker: string;
  sector: string;
  country: string;
  market?: string;
};

export const STOCK_LIST: StockItem[] = [
  // ── KOSPI ───────────────────────────────────────────────────────────────
  { name: '삼성전자',           ticker: '005930', sector: 'IT/반도체',   country: 'kr', market: 'KOSPI' },
  { name: 'SK하이닉스',         ticker: '000660', sector: 'IT/반도체',   country: 'kr', market: 'KOSPI' },
  { name: 'LG에너지솔루션',     ticker: '373220', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: '삼성바이오로직스',   ticker: '207940', sector: '바이오',      country: 'kr', market: 'KOSPI' },
  { name: '현대차',             ticker: '005380', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: '삼성SDI',            ticker: '006400', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: 'LG화학',             ticker: '051910', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: 'POSCO홀딩스',        ticker: '005490', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '카카오',             ticker: '035720', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSPI' },
  { name: '현대모비스',         ticker: '012330', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: 'KB금융',             ticker: '105560', sector: '금융',        country: 'kr', market: 'KOSPI' },
  { name: '신한지주',           ticker: '055550', sector: '금융',        country: 'kr', market: 'KOSPI' },
  { name: '셀트리온',           ticker: '068270', sector: '바이오',      country: 'kr', market: 'KOSPI' },
  { name: 'LG전자',             ticker: '066570', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: 'NAVER',              ticker: '035420', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSPI' },
  { name: '기아',               ticker: '000270', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: 'SK이노베이션',       ticker: '096770', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: '하나금융지주',       ticker: '086790', sector: '금융',        country: 'kr', market: 'KOSPI' },
  { name: 'SK텔레콤',           ticker: '017670', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSPI' },
  { name: 'KT',                 ticker: '030200', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSPI' },
  { name: 'KT&G',               ticker: '033780', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: '우리금융지주',       ticker: '316140', sector: '금융',        country: 'kr', market: 'KOSPI' },
  { name: '한국전력',           ticker: '015760', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: '삼성물산',           ticker: '028260', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: 'SK',                 ticker: '034730', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '카카오뱅크',         ticker: '323410', sector: '금융',        country: 'kr', market: 'KOSPI' },
  { name: 'LG',                 ticker: '003550', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '포스코퓨처엠',       ticker: '003670', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: '한화에어로스페이스', ticker: '012450', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '두산에너빌리티',     ticker: '034020', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: '고려아연',           ticker: '010130', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '한국항공우주',       ticker: '047810', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '현대중공업',         ticker: '329180', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '크래프톤',           ticker: '259960', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSPI' },
  { name: '카카오페이',         ticker: '377300', sector: '금융',        country: 'kr', market: 'KOSPI' },
  { name: '삼성생명',           ticker: '032830', sector: '금융',        country: 'kr', market: 'KOSPI' },
  { name: 'GS',                 ticker: '078930', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: 'S-Oil',              ticker: '010950', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: '롯데케미칼',         ticker: '011170', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '한국가스공사',       ticker: '036460', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: 'DB하이텍',           ticker: '000990', sector: 'IT/반도체',   country: 'kr', market: 'KOSPI' },
  { name: '삼성전기',           ticker: '009150', sector: 'IT/반도체',   country: 'kr', market: 'KOSPI' },
  { name: '한온시스템',         ticker: '018880', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: 'LS ELECTRIC',        ticker: '010120', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: '현대건설',           ticker: '000720', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: 'GS건설',             ticker: '006360', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '삼성SDS',            ticker: '018260', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSPI' },
  { name: 'LG이노텍',           ticker: '011070', sector: 'IT/반도체',   country: 'kr', market: 'KOSPI' },
  { name: '삼성화재',           ticker: '000810', sector: '금융',        country: 'kr', market: 'KOSPI' },
  { name: '아모레퍼시픽',       ticker: '090430', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: 'LG생활건강',         ticker: '051900', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: '한미약품',           ticker: '128940', sector: '바이오',      country: 'kr', market: 'KOSPI' },
  { name: '오리온',             ticker: '271560', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: 'CJ제일제당',         ticker: '097950', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: '대한항공',           ticker: '003490', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '현대글로비스',       ticker: '086280', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: '엔씨소프트',         ticker: '036570', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSPI' },
  { name: '하이브',             ticker: '352820', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: '코웨이',             ticker: '021240', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: 'LG디스플레이',       ticker: '034220', sector: 'IT/반도체',   country: 'kr', market: 'KOSPI' },
  { name: '현대제철',           ticker: '004020', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '이마트',             ticker: '139480', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: '롯데쇼핑',           ticker: '023530', sector: '소비재',      country: 'kr', market: 'KOSPI' },
  { name: '한국조선해양',       ticker: '009540', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '현대로템',           ticker: '064350', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '녹십자',             ticker: '006280', sector: '바이오',      country: 'kr', market: 'KOSPI' },
  { name: 'SK바이오팜',         ticker: '326030', sector: '바이오',      country: 'kr', market: 'KOSPI' },
  { name: '삼성중공업',         ticker: '010140', sector: '기타',        country: 'kr', market: 'KOSPI' },
  { name: '코스모화학',         ticker: '005420', sector: '에너지',      country: 'kr', market: 'KOSPI' },
  { name: '한국타이어앤테크놀로지', ticker: '161390', sector: '소비재',  country: 'kr', market: 'KOSPI' },

  // ── KOSDAQ ──────────────────────────────────────────────────────────────
  { name: '에코프로비엠',       ticker: '247540', sector: '에너지',      country: 'kr', market: 'KOSDAQ' },
  { name: '에코프로',           ticker: '086520', sector: '에너지',      country: 'kr', market: 'KOSDAQ' },
  { name: 'HLB',               ticker: '028300', sector: '바이오',      country: 'kr', market: 'KOSDAQ' },
  { name: '알테오젠',           ticker: '196170', sector: '바이오',      country: 'kr', market: 'KOSDAQ' },
  { name: '리노공업',           ticker: '058470', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '클래시스',           ticker: '214150', sector: '바이오',      country: 'kr', market: 'KOSDAQ' },
  { name: '주성엔지니어링',     ticker: '036930', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '레인보우로보틱스',   ticker: '277810', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '파마리서치',         ticker: '214450', sector: '바이오',      country: 'kr', market: 'KOSDAQ' },
  { name: '셀트리온헬스케어',   ticker: '091990', sector: '바이오',      country: 'kr', market: 'KOSDAQ' },
  { name: '엔켐',               ticker: '348370', sector: '에너지',      country: 'kr', market: 'KOSDAQ' },
  { name: '카카오게임즈',       ticker: '293490', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSDAQ' },
  { name: '펄어비스',           ticker: '263750', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSDAQ' },
  { name: '넷마블',             ticker: '251270', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSDAQ' },
  { name: 'HPSP',               ticker: '403870', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '이오테크닉스',       ticker: '039030', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '솔브레인',           ticker: '357780', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '엘앤에프',           ticker: '066970', sector: '에너지',      country: 'kr', market: 'KOSDAQ' },
  { name: '씨에스윈드',         ticker: '112610', sector: '에너지',      country: 'kr', market: 'KOSDAQ' },
  { name: '케이씨텍',           ticker: '064760', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '원익IPS',            ticker: '240810', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '덕산네오룩스',       ticker: '213420', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '피에스케이',         ticker: '319660', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '오스템임플란트',     ticker: '048260', sector: '바이오',      country: 'kr', market: 'KOSDAQ' },
  { name: '비에이치',           ticker: '090460', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: 'SM엔터테인먼트',     ticker: '041510', sector: '소비재',      country: 'kr', market: 'KOSDAQ' },
  { name: 'YG엔터테인먼트',     ticker: '122870', sector: '소비재',      country: 'kr', market: 'KOSDAQ' },
  { name: '컴투스',             ticker: '078340', sector: 'IT/플랫폼',  country: 'kr', market: 'KOSDAQ' },
  { name: '셀트리온제약',       ticker: '068760', sector: '바이오',      country: 'kr', market: 'KOSDAQ' },
  { name: '서울반도체',         ticker: '046890', sector: 'IT/반도체',   country: 'kr', market: 'KOSDAQ' },
  { name: '메디톡스',           ticker: '086900', sector: '바이오',      country: 'kr', market: 'KOSDAQ' },

  // ── 국내 ETF ────────────────────────────────────────────────────────────
  { name: 'KODEX 200',                   ticker: '069500', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'TIGER 200',                   ticker: '102110', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'KODEX 레버리지',              ticker: '122630', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'KODEX 인버스',                ticker: '114800', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'KODEX 반도체',                ticker: '091160', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'TIGER 나스닥100',             ticker: '133690', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'KODEX 미국S&P500TR',          ticker: '379800', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'KODEX 미국S&P500',            ticker: '360200', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'TIGER 미국S&P500',            ticker: '360750', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'KODEX 미국나스닥100TR',       ticker: '379810', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'ACE 미국나스닥100',           ticker: '367380', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'KODEX 금액티브 (Gold)',       ticker: '411060', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'KODEX 2차전지산업',           ticker: '305720', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'TIGER 차이나전기차SOLACTIVE', ticker: '371460', sector: 'ETF', country: 'kr', market: 'ETF' },
  { name: 'KODEX 코스닥150',             ticker: '229200', sector: 'ETF', country: 'kr', market: 'ETF' },

  // ── 미국 (US) ───────────────────────────────────────────────────────────
  { name: 'Apple (애플)',        ticker: 'AAPL',  sector: 'IT/반도체',   country: 'us', market: 'NASDAQ' },
  { name: 'Microsoft (마이크로소프트)', ticker: 'MSFT', sector: 'IT/플랫폼', country: 'us', market: 'NASDAQ' },
  { name: 'NVIDIA (엔비디아)',   ticker: 'NVDA',  sector: 'IT/반도체',   country: 'us', market: 'NASDAQ' },
  { name: 'Amazon (아마존)',     ticker: 'AMZN',  sector: 'IT/플랫폼',  country: 'us', market: 'NASDAQ' },
  { name: 'Alphabet / 알파벳',  ticker: 'GOOGL', sector: 'IT/플랫폼',  country: 'us', market: 'NASDAQ' },
  { name: 'Alphabet (GOOG)',     ticker: 'GOOG',  sector: 'IT/플랫폼',  country: 'us', market: 'NASDAQ' },
  { name: 'Meta (메타)',         ticker: 'META',  sector: 'IT/플랫폼',  country: 'us', market: 'NASDAQ' },
  { name: 'Tesla (테슬라)',      ticker: 'TSLA',  sector: '소비재',      country: 'us', market: 'NASDAQ' },
  { name: 'AMD',                 ticker: 'AMD',   sector: 'IT/반도체',   country: 'us', market: 'NASDAQ' },
  { name: 'Netflix (넷플릭스)', ticker: 'NFLX',  sector: 'IT/플랫폼',  country: 'us', market: 'NASDAQ' },
  { name: 'Broadcom (브로드컴)',ticker: 'AVGO',  sector: 'IT/반도체',   country: 'us', market: 'NASDAQ' },
  { name: 'Qualcomm (퀄컴)',    ticker: 'QCOM',  sector: 'IT/반도체',   country: 'us', market: 'NASDAQ' },
  { name: 'Intel (인텔)',        ticker: 'INTC',  sector: 'IT/반도체',   country: 'us', market: 'NASDAQ' },
  { name: 'Costco (코스트코)',  ticker: 'COST',  sector: '소비재',      country: 'us', market: 'NASDAQ' },
  { name: 'TSMC',               ticker: 'TSM',   sector: 'IT/반도체',   country: 'us', market: 'NYSE' },
  { name: 'JP Morgan Chase',    ticker: 'JPM',   sector: '금융',        country: 'us', market: 'NYSE' },
  { name: 'Visa',               ticker: 'V',     sector: '금융',        country: 'us', market: 'NYSE' },
  { name: 'Mastercard',         ticker: 'MA',    sector: '금융',        country: 'us', market: 'NYSE' },
  { name: 'Exxon Mobil',        ticker: 'XOM',   sector: '에너지',      country: 'us', market: 'NYSE' },
  { name: 'Johnson & Johnson',  ticker: 'JNJ',   sector: '바이오',      country: 'us', market: 'NYSE' },
  { name: 'Eli Lilly',          ticker: 'LLY',   sector: '바이오',      country: 'us', market: 'NYSE' },
  { name: 'UnitedHealth',       ticker: 'UNH',   sector: '바이오',      country: 'us', market: 'NYSE' },
  { name: 'Pfizer',             ticker: 'PFE',   sector: '바이오',      country: 'us', market: 'NYSE' },
  { name: 'Berkshire Hathaway', ticker: 'BRK-B', sector: '금융',        country: 'us', market: 'NYSE' },
  { name: 'Walmart',            ticker: 'WMT',   sector: '소비재',      country: 'us', market: 'NYSE' },
  { name: 'Disney',             ticker: 'DIS',   sector: '소비재',      country: 'us', market: 'NYSE' },
  { name: 'Salesforce',         ticker: 'CRM',   sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Oracle',             ticker: 'ORCL',  sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Uber',               ticker: 'UBER',  sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Airbnb',             ticker: 'ABNB',  sector: '소비재',      country: 'us', market: 'NASDAQ' },
  { name: 'Moderna',            ticker: 'MRNA',  sector: '바이오',      country: 'us', market: 'NASDAQ' },
  { name: 'Coupang',            ticker: 'CPNG',  sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Block (Square)',     ticker: 'SQ',    sector: '금융',        country: 'us', market: 'NYSE' },
  { name: 'Spotify',            ticker: 'SPOT',  sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Palantir',           ticker: 'PLTR',  sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Snowflake',          ticker: 'SNOW',  sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Chevron',            ticker: 'CVX',   sector: '에너지',      country: 'us', market: 'NYSE' },
  { name: 'Palo Alto Networks', ticker: 'PANW',  sector: 'IT/플랫폼',  country: 'us', market: 'NASDAQ' },
  { name: 'Shopify',            ticker: 'SHOP',  sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Coinbase',           ticker: 'COIN',  sector: '금융',        country: 'us', market: 'NASDAQ' },
  { name: 'ARM Holdings',       ticker: 'ARM',   sector: 'IT/반도체',   country: 'us', market: 'NASDAQ' },
  { name: 'CrowdStrike',        ticker: 'CRWD',  sector: 'IT/플랫폼',  country: 'us', market: 'NASDAQ' },
  { name: 'ServiceNow',         ticker: 'NOW',   sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Adobe',              ticker: 'ADBE',  sector: 'IT/플랫폼',  country: 'us', market: 'NASDAQ' },
  { name: 'Intuit',             ticker: 'INTU',  sector: 'IT/플랫폼',  country: 'us', market: 'NASDAQ' },
  { name: 'PayPal',             ticker: 'PYPL',  sector: '금융',        country: 'us', market: 'NASDAQ' },
  { name: 'Booking Holdings',   ticker: 'BKNG',  sector: '소비재',      country: 'us', market: 'NASDAQ' },
  { name: 'Nike',               ticker: 'NKE',   sector: '소비재',      country: 'us', market: 'NYSE' },
  { name: 'Starbucks',          ticker: 'SBUX',  sector: '소비재',      country: 'us', market: 'NASDAQ' },
  { name: "McDonald's",         ticker: 'MCD',   sector: '소비재',      country: 'us', market: 'NYSE' },
  { name: 'Caterpillar',        ticker: 'CAT',   sector: '기타',        country: 'us', market: 'NYSE' },
  { name: 'AT&T',               ticker: 'T',     sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Verizon',            ticker: 'VZ',    sector: 'IT/플랫폼',  country: 'us', market: 'NYSE' },
  { name: 'Realty Income',      ticker: 'O',     sector: '금융',        country: 'us', market: 'NYSE' },
  { name: 'American Tower',     ticker: 'AMT',   sector: '금융',        country: 'us', market: 'NYSE' },
  { name: 'Intuitive Surgical', ticker: 'ISRG',  sector: '바이오',      country: 'us', market: 'NASDAQ' },

  // ── 미국 ETF ────────────────────────────────────────────────────────────
  { name: 'SPY (S&P500 ETF)',       ticker: 'SPY',  sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'QQQ (NASDAQ-100 ETF)',   ticker: 'QQQ',  sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'VOO (Vanguard S&P500)',  ticker: 'VOO',  sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'VTI (Total Market ETF)', ticker: 'VTI',  sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'SCHD (Dividend ETF)',    ticker: 'SCHD', sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'JEPI (Income ETF)',      ticker: 'JEPI', sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'QQQM (NASDAQ-100 mini)', ticker: 'QQQM', sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'ARKK (ARK Innovation)', ticker: 'ARKK', sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'IVV (iShares S&P500)',                    ticker: 'IVV',  sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'TQQQ (3x NASDAQ ETF)',                    ticker: 'TQQQ', sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'QLD (2x NASDAQ-100 ProShares)',            ticker: 'QLD',  sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'SOXL (반도체 3배 Direxion)',               ticker: 'SOXL', sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'SOXS (반도체 3배 인버스 Direxion)',        ticker: 'SOXS', sector: 'ETF', country: 'us', market: 'ETF' },
  { name: 'TECL (테크 3배 Direxion)',                 ticker: 'TECL', sector: 'ETF', country: 'us', market: 'ETF' },
];

export const CRYPTO_LIST: StockItem[] = [
  { name: '비트코인',    ticker: 'BTC',   sector: '가상자산', country: 'crypto' },
  { name: '이더리움',    ticker: 'ETH',   sector: '가상자산', country: 'crypto' },
  { name: '리플',        ticker: 'XRP',   sector: '가상자산', country: 'crypto' },
  { name: '솔라나',      ticker: 'SOL',   sector: '가상자산', country: 'crypto' },
  { name: '바이낸스코인',ticker: 'BNB',   sector: '가상자산', country: 'crypto' },
  { name: '에이다',      ticker: 'ADA',   sector: '가상자산', country: 'crypto' },
  { name: '도지코인',    ticker: 'DOGE',  sector: '가상자산', country: 'crypto' },
  { name: '트론',        ticker: 'TRX',   sector: '가상자산', country: 'crypto' },
  { name: '톤코인',      ticker: 'TON',   sector: '가상자산', country: 'crypto' },
  { name: '수이',        ticker: 'SUI',   sector: '가상자산', country: 'crypto' },
  { name: '앱토스',      ticker: 'APT',   sector: '가상자산', country: 'crypto' },
  { name: '폴리곤',      ticker: 'POL',   sector: '가상자산', country: 'crypto' },
  { name: '체인링크',    ticker: 'LINK',  sector: '가상자산', country: 'crypto' },
  { name: '아발란체',    ticker: 'AVAX',  sector: '가상자산', country: 'crypto' },
  { name: '옵티미즘',    ticker: 'OP',    sector: '가상자산', country: 'crypto' },
  { name: '아비트럼',    ticker: 'ARB',   sector: '가상자산', country: 'crypto' },
  { name: '인젝티브',    ticker: 'INJ',   sector: '가상자산', country: 'crypto' },
  { name: '니어프로토콜',ticker: 'NEAR',  sector: '가상자산', country: 'crypto' },
  { name: '유니스왑',    ticker: 'UNI',   sector: '가상자산', country: 'crypto' },
  { name: '코스모스',    ticker: 'ATOM',  sector: '가상자산', country: 'crypto' },
  { name: '스텔라루멘',  ticker: 'XLM',   sector: '가상자산', country: 'crypto' },
  { name: '클레이튼',    ticker: 'KLAY',  sector: '가상자산', country: 'crypto' },
  { name: '위믹스',      ticker: 'WEMIX', sector: '가상자산', country: 'crypto' },
  { name: '시바이누',    ticker: 'SHIB',  sector: '가상자산', country: 'crypto' },
  { name: '페페',        ticker: 'PEPE',  sector: '가상자산', country: 'crypto' },
  { name: '샌드박스',    ticker: 'SAND',  sector: '가상자산', country: 'crypto' },
  { name: '월드코인',    ticker: 'WLD',   sector: '가상자산', country: 'crypto' },
];

/** 이름 또는 티커로 검색 (대소문자 무시) */
export function searchStocks(query: string, type: 'stock' | 'crypto' | 'gold'): StockItem[] {
  if (type === 'gold' || !query.trim()) return [];
  const list = type === 'crypto' ? CRYPTO_LIST : STOCK_LIST;
  const q = query.toLowerCase().trim();

  // 티커 완전 일치를 최상위로
  const exact = list.filter(s => s.ticker.toLowerCase() === q);
  const starts = list.filter(s =>
    s.ticker.toLowerCase() !== q &&
    (s.ticker.toLowerCase().startsWith(q) || s.name.toLowerCase().startsWith(q))
  );
  const contains = list.filter(s =>
    s.ticker.toLowerCase() !== q &&
    !s.ticker.toLowerCase().startsWith(q) &&
    !s.name.toLowerCase().startsWith(q) &&
    (s.name.toLowerCase().includes(q) || s.ticker.toLowerCase().includes(q))
  );

  return [...exact, ...starts, ...contains];
}
